export const services = [
  { name: "Emergency Dentistry", icon: "/Images/icons/emergency denstiry.png", link: "/services/emergency-dentistry" },
  { name: "Root Canal", icon: "/Images/icons/root-canal.png", link: "/services/root-canal" },
  { name: "Oral Surgery", icon: "/Images/icons/oral surgery.png", link: "/services/oral-surgery" },
  { name: "Cosmetic Dentistry", icon: "/Images/icons/Cosmetic dentistry.png", link: "/services/cosmetic-dentistry" },
  { name: "Dental Fillings", icon: "/Images/icons/tooth-filling.png", link: "/services/dental-fillings" },
  { name: "Dental Implants", icon: "/Images/icons/implant.png", link: "/services/dental-implants" },
  { name: "Orthodontics", icon: "/Images/icons/orthodontics.png", link: "/services/orthodontics" },
  { name: "Crowns and Bridges", icon: "/Images/icons/dental-crown.png", link: "/services/crowns-and-bridges" },
  { name: "Dental Emergencies", icon: "/Images/icons/emergency denstiry.png", link: "/services/dental-emergencies" },
  { name: "Tooth Extraction", icon: "/Images/icons/tooth-extraction.png", link: "/services/tooth-extraction" },
  { name: "Whitening & Veneers", icon: "/Images/icons/tooth-whitening.png", link: "/services/whitening-&-veneers" },
  { name: "Invisalign", icon: "/Images/icons/Invisalign.png", link: "/services/invisalign" },
  { name: "Kids & Children Dentistry", icon: "/Images/icons/braces.png", link: "/services/kids-&-children-dentistry" },
  { name: "Permanent Teeth Replacement", icon: "/Images/icons/Teeth Replacement.png", link: "/services/permanent-teeth-replacement" },
  { name: "Sports Dentistry", icon: "/Images/icons/sports dentistry.png", link: "/services/sports-dentistry" },
  { name: "Wisdom Teeth", icon: "/Images/icons/wisdom teeth.png", link: "/services/wisdom-teeth-removal" },
  { name: "Endodontics", icon: "/Images/icons/endodontics.png", link: "/services/endodontics" },
  { name: "Same-Day-Dentistry", icon: "/Images/icons/same-day-dentistry.png", link: "/services/same-day-dentistry" },
  { name: "Painless Treatment", icon: "/Images/icons/painless dentistry.png", link: "/services/painless-treatment" },
  { name: "Perio Protect", icon: "/Images/icons/perio protect.png", link: "/services/perio-protect" },
  { name: "Halitosis", icon: "/Images/icons/tooth-whitening.png", link: "/services/halitosis" },
]; 